travis:
  secure:
    BINSTAR_TOKEN: jKRb8OI5vVn2tNs9d+3pNgZHLraxPzu4241n9SDJROQVkHfkH7t3Nk4Sozx+sYiLIDHxolltamNxrwaXAT3hfytKpiIDrqARNPzqXtFqC9sf8sU4jOeNm1h0JVO7qvJ1djahlXCFfRh9Xf6/PRdN3u3XaI0MFUBm/ihWGnQOPP/OlmNBTf5wTsTrXWyB+U3d3FBb7d5ATGSm5q9VApawPZUshDoZBGWGTOiH7RoMQDcM0/EyF7d1q50b9+Ebg8DqSgLz3lbLNMgKASXPlZ2jv7u4WhuGGH1AvGd5y59hfbWecbVIlboUykBLHa1sNmvNwhOOEWdMrkONCOVLY8CWBV95o/S8BBjO8XbBKADOfdJJoWBkTKwyRaBkxnNx2Baj8+sDEfR4NVlVvwoxFfzuvXBRHijg3G7CoTbMbrkukGT6Qn6Vi7+lFtW0LjXgbfBiMldI/0W44D20Za7NU89al0sLA22kFvuvxEPY3jMjmUi3CXtrv04O5a0p/naksjvX+lvsuolHFmftG75giDMfMr9JIMdhqXpu6ox8TXYKygtrf0167znodt5kQ8oTNDe2x4PVodCVMvbueRLkm4x5ALqXd+gDKwO/nzZhEIC6UtX4WBCugTB36j+Pm0Ibtysv6ms3s6E+mE7Cg1RGYIkqBkryjOTPxomlPMY0EoeA4a8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
